const actionsEnum = {
  CHANGE_SEARCH_KEY: 'CHANGE_SEARCH_KEY',
  SEARCH_STARTED: 'SEARCH_STARTED',
  SEARCH_COMPLETED: 'SEARCH_COMPLETED',
  CHANGE_SELECTED_RECIPE: 'CHANGE_SELECTED_RECIPE',
};

export default actionsEnum;
